FROM python:3.10-slim
WORKDIR /app
RUN pip install --no-cache-dir flask prometheus-client numpy pandas scikit-learn joblib xgboost lightgbm
COPY monitoring/inference_api.py .
COPY models/ ./models/
EXPOSE 5000
CMD ["python", "inference_api.py"]